INSERT INTO user(firstName, lastName, email, gender) VALUES
	("João", "Silva", "joao.silva@example.com", "1"),
	("Maria", "Santos", "maria.santos@example.com", "2"),
	("Pedro", "Ferreira", "pedro.ferreira@example.com", "1"),
	("Ana", "Oliveira", "ana.oliveira@example.com", "2"),
	("Luiz", "Garcia", "luiz.garcia@example.com", "1"),
	("Camila", "Rodrigues", "camila.rodrigues@example.com", "2"),
	("Rafael", "Martins", "rafael.martins@example.com", "1"),
	("Julia", "Lima", "julia.lima@example.com", "2"),
	("Lucas", "Fernandes", "lucas.fernandes@example.com", "1"),
	("Beatriz", "Almeida", "beatriz.almeida@example.com", "2"),
	("Mateus", "Ribeiro", "mateus.ribeiro@example.com", "1"),
	("Larissa", "Carvalho", "larissa.carvalho@example.com", "2"),
	("Enzo", "Sousa", "enzo.sousa@example.com", "1"),
	("Isabela", "Gomes", "isabela.gomes@example.com", "2"),
	("Leonardo", "Lopes", "leonardo.lopes@example.com", "1"),
	("Clara", "Nunes", "clara.nunes@example.com", "2"),
	("Gabriel", "Machado", "gabriel.machado@example.com", "1"),
	("Laura", "Cruz", "laura.cruz@example.com", "2"),
	("Matheus", "Dias", "matheus.dias@example.com", "1"),
	("Sophia", "Ferreira", "sophia.ferreira@example.com", "2"),
	("Davi", "Santos", "davi.santos@example.com", "1"),
	("Helena", "Lima", "helena.lima@example.com", "2"),
	("Samuel", "Costa", "samuel.costa@example.com", "1"),
	("Valentina", "Ribeiro", "valentina.ribeiro@example.com", "2"),
	("Lucas", "Sousa", "lucas.sousa@example.com", "1"),
	("Maria Eduarda", "Oliveira", "maria.eduarda.oliveira@example.com", "2"),
	("Lorenzo", "Martins", "lorenzo.martins@example.com", "1"),
	("Lívia", "Cavalcanti", "livia.cavalcanti@example.com", "2"),
	("Guilherme", "Pereira", "guilherme.pereira@example.com", "1"),
	("Giovanna", "Rodrigues", "giovanna.rodrigues@example.com", "2"),
	("Pedro Henrique", "Alves", "pedro.henrique.alves@example.com", "1"),
	("Isabella", "Carvalho", "isabella.carvalho@example.com", "2"),
	("Murilo", "Nascimento", "murilo.nascimento@example.com", "1"),
	("Juliana", "Gonçalves", "juliana.goncalves@example.com", "2"),
	("Gustavo", "Araújo", "gustavo.araujo@example.com", "1"),
	("Vitória", "Sousa", "vitoria.sousa@example.com", "2"),
	("Antônio", "Fernandes", "antonio.fernandes@example.com", "1"),
	("Carolina", "Lopes", "carolina.lopes@example.com", "2"),
	("Enzo Gabriel", "Machado", "enzo.gabriel.machado@example.com", "1"),
	("Laura Beatriz", "Carvalho", "laura.beatriz.carvalho@example.com", "2"),
	("Lucas Vinícius", "Oliveira", "lucas.vinicius.oliveira@example.com", "1"),
	("Sophia Maria", "Santos", "sophia.maria.santos@example.com", "2"),
	("Rafaela", "Pereira", "rafaela.pereira@example.com", "2"),
	("Matheus Henrique", "Gomes", "matheus.henrique.gomes@example.com", "1"),
	("Ana Clara", "Rodrigues", "ana.clara.rodrigues@example.com", "2"),
	("José Carlos", "Almeida", "jose.carlos.almeida@example.com", "1"),
	("Helena Beatriz", "Silva", "helena.beatriz.silva@example.com", "2"),
	("Davi Luiz", "Costa", "davi.luiz.costa@example.com", "1"),
	("Marina", "Ferreira", "marina.ferreira@example.com", "2"),
	("João Miguel", "Nascimento", "joao.miguel.nascimento@example.com", "1"),
	("Clara Sophia", "Gonçalves", "clara.sophia.goncalves@example.com", "2"),
	("Pedro Lucas", "Araújo", "pedro.lucas.araujo@example.com", "1"),
	("Isadora", "Sousa", "isadora.sousa@example.com", "2"),
	("Lucas Gabriel", "Fernandes", "lucas.gabriel.fernandes@example.com", "1"),
	("Ana Júlia", "Lopes", "ana.julia.lopes@example.com", "2"),
	("Raul", "Machado", "raul.machado@example.com", "1"),
	("Gabriela", "Carvalho", "gabriela.carvalho@example.com", "2"),
	("Eduardo", "Oliveira", "eduardo.oliveira@example.com", "1"),
	("Ana Luiza", "Santos", "ana.luiza.santos@example.com", "2"),
	("Luiz Gustavo", "Pereira", "luiz.gustavo.pereira@example.com", "1"),
	("Melissa", "Rodrigues", "melissa.rodrigues@example.com", "2"),
	("Lucas Gabriel", "Alves", "lucas.gabriel.alves@example.com", "1"),
	("Manuela", "Carvalho", "manuela.carvalho@example.com", "2"),
	("Lucca", "Nascimento", "lucca.nascimento@example.com", "1"),
	("Isabelly", "Gonçalves", "isabelly.goncalves@example.com", "2"),
	("Vinícius", "Araújo", "vinicius.araujo@example.com", "1"),
	("Eloá", "Sousa", "eloa.sousa@example.com", "2"),
	("Luan", "Fernandes", "luan.fernandes@example.com", "1"),
	("Clara Vitória", "Lopes", "clara.vitoria.lopes@example.com", "2"),
	("Felipe", "Machado", "felipe.machado@example.com", "1"),
	("Maria Fernanda", "Carvalho", "maria.fernanda.carvalho@example.com", "2");